Repository connect-foundation/2019-16, pull requests merged in 2019-12, with the labels that each got.

#146 로그서비스로 로그 패킷 전송 후 엘라스틱서치 저장
  server/api-gateway/index.js
  server/api-gateway/middleware/middleware-logger.js
  server/lib/tcp/App.js
  server/lib/tcp/logUtils.js
  server/lib/tcp/tcpClient.js
  server/lib/tcp/tcpServer.js
  server/services/log/index.js
  server/services/log/package.json
  server/services/search/Search.js
  server/services/search/index.js
Labels: automerge

#155 packet에 endquery 추가
  server/api-gateway/index.js
  server/api-gateway/middleware/middleware-logger.js
  server/api-gateway/routes/search.js
  server/api-gateway/routes/studyGroup.js
  server/lib/tcp/App.js
  server/lib/tcp/util.js
  server/services/applistmanager/AppListManager.js
  server/services/search/Search.js
Labels: automerge

#163 클라이언트 파일 및 컴포넌트 구조 변경
  client/src/App.js
  client/src/components/users/Header.jsx
  client/src/components/users/accountContainer/LoginButton.jsx
  client/src/components/users/accountContainer/LogoutButton.jsx
  client/src/components/users/accountContainer/UserInfo.jsx
  client/src/components/users/accountContainer/index.jsx
  client/src/components/users/common/EmailInput.jsx
  client/src/components/users/common/Location.jsx
  client/src/components/users/common/SubmitButton.jsx
  client/src/components/users/common/TagButtons.jsx
  client/src/components/users/groupCard/Body.jsx
  client/src/components/users/groupCard/Footer.jsx
  client/src/components/users/groupCard/Personnel.jsx
  client/src/components/users/groupCard/Subtitle.jsx
  client/src/components/users/groupCard/Thumbnail.jsx
  client/src/components/users/groupCard/Time.jsx
  client/src/components/users/groupCard/Title.jsx
  client/src/components/users/groupCard/index.jsx
  client/src/components/users/groupCreate/Category.jsx
  client/src/components/users/groupCreate/ImageUploader.jsx
  client/src/components/users/groupCreate/ScheduleInput.jsx
  client/src/components/users/groupCreate/TagInput.jsx
  client/src/components/users/groupDetail/Header.jsx
  client/src/components/users/groupDetail/Intro.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/components/users/studySearchNavbar/StudyNavbarItem.jsx
  client/src/components/users/studySearchNavbar/StudySearchNavbar.jsx
  client/src/config.json
  client/src/pages/partners/index.jsx
  client/src/pages/users/AppContainer.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/index.jsx
  client/src/reducer/App.jsx
  client/src/reducer/AppContainer.jsx
  client/src/reducer/Main.jsx
  client/src/reducer/users/groupCreate.jsx
  client/src/reducer/users/groupDetail.jsx
  client/src/reducer/users/index.jsx
Labels: FE, Refactoring, structure

#177 구조 리팩토링한 후의 메인 페이지 정리
  client/src/components/users/Header.jsx
  client/src/components/users/common/Location.jsx
  client/src/components/users/groupCard/Footer.jsx
  client/src/components/users/groupCard/Time.jsx
  client/src/components/users/groupDetail/Header.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/components/users/studySearchNavbar/StudyNavbarItem.jsx
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/index.jsx
  client/src/reducer/users/groupDetail.jsx
  client/src/reducer/users/index.jsx
Labels: automerge

#198 사용자 로그인 컴포넌트 리팩토링
  client/package.json
  client/src/components/users/Header.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/index.jsx
  client/src/config.json
  client/src/pages/users/index.jsx
  server/api-gateway/README.md
Labels: FE, Refactoring

#191 반복문을 비동기 재귀함수로 수정
  server/services/search/elasticsearch.js
  server/services/search/test/search.test.js
Labels: automerge

#204 Page/main 카카오 로그인 기능 구현
  client/package.json
  client/src/components/users/Header.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/index.jsx
  client/src/config.json
  client/src/pages/users/index.jsx
  server/api-gateway/README.md
Labels: MergeToDevelop

#203 스터디 개설 뷰
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/components/users/common/RangeSlider.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/reducer/users/groupCreate.jsx
Labels: MergeToDevelop

#202 스터디 개설 서비스
  server/api-gateway/index.js
  server/api-gateway/routes/studyGroup.js
  server/services/studygroup/StudyGroup.js
  server/services/studygroup/index.js
  server/services/studygroup/models/StudyGroups.js
Labels: automerge

#205 Service/search 서치 서비스 리펙토림
  server/services/search/README.md
  server/services/search/elasticsearch.js
  server/services/search/test/search.test.js
Labels: MergeToDevelop

#206 Service/study group 스터디 개설 서비스 리펙토링
  server/api-gateway/index.js
  server/api-gateway/routes/studyGroup.js
  server/services/studygroup/README.md
  server/services/studygroup/StudyGroup.js
  server/services/studygroup/index.js
  server/services/studygroup/models/StudyGroups.js
Labels: MergeToDevelop

#214 Service/study group
  server/api-gateway/index.js
  server/api-gateway/lib/setObjectStorage.js
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/api-gateway/routes/api/studyGroup/index.js
  server/api-gateway/routes/studyGroup.js
  server/services/studygroup/StudyGroup.js
Labels: MergeToDevelop

#217 Develop/server
  server/api-gateway/index.js
  server/api-gateway/lib/setObjectStorage.js
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/api-gateway/routes/api/studyGroup/index.js
  server/api-gateway/routes/studyGroup.js
  server/lib/redis/index.js
  server/services/search/README.md
  server/services/search/elasticsearch.js
  server/services/search/test/search.test.js
  server/services/studygroup/README.md
  server/services/studygroup/StudyGroup.js
  server/services/studygroup/index.js
  server/services/studygroup/models/StudyGroups.js
Labels: 서비스업데이트

#221 Page/group detail
  client/src/components/users/groupCard/Footer.jsx
  client/src/components/users/groupCard/Time.jsx
  client/src/components/users/groupDetail/Intro.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/reducer/users/groupCreate.jsx
Labels: MergeToDevelop

#222 Service/study group
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/services/search/elasticsearch.js
  server/services/studygroup/StudyGroup.js
Labels: MergeToDevelop

#224 Service/gateway
  server/api-gateway/README.md
  server/api-gateway/index.js
  server/api-gateway/middleware/payment/payQueueInspection.js
  server/api-gateway/middleware/payment/readyToPay.js
  server/api-gateway/package.json
  server/api-gateway/routes/api/index.js
  server/api-gateway/routes/api/payment/index.js
Labels: MergeToDevelop

#282 test 코드 작성 및 버그 수정
  server/services/search/elasticsearch.js
  server/services/search/test/search.test.js
Labels: automerge

#283 권한 확인 미들웨어 작성 및 모듈 테스트
  server/api-gateway/auth/passport.js
  server/api-gateway/index.js
  server/api-gateway/lib/getRoleFromToken.js
  server/api-gateway/middleware/auth/token-parser.js
  server/api-gateway/package-lock.json
  server/api-gateway/package.json
  server/api-gateway/routes/auth.partners.js
  server/api-gateway/routes/auth.users.js
  server/api-gateway/routes/auth/index.js
  server/api-gateway/routes/auth/partners.js
  server/api-gateway/routes/auth/users.js
  server/api-gateway/test/getRoleFromToken.test.js
Labels: automerge

#299 스터디룸 검색 서비스 개발
  server/api-gateway/routes/studyRoom.js
  server/lib/tcp/util.js
  server/package-lock.json
  server/package.json
  server/services/studyroom/README.md
  server/services/studyroom/StudyRoom.js
  server/services/studyroom/jest-mongodb-config.js
  server/services/studyroom/jest.config.js
  server/services/studyroom/package-lock.json
  server/services/studyroom/package.json
  server/services/studyroom/queryResolver.js
  server/services/studyroom/test/study.test.js
Labels: automerge

#287 그룹 삭제에 대한 요청 응답
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/api-gateway/routes/api/studyGroup/index.js
  server/services/studygroup/StudyGroup.js
Labels: BE, Group, automerge

#298 reservation filtering 및 통신 모듈 프로토콜 수정
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/api-gateway/routes/search.js
  server/lib/tcp/App.js
  server/lib/tcp/logUtils.js
  server/lib/tcp/util.js
  server/services/applistmanager/AppListManager.js
  server/services/log/index.js
  server/services/reservation/Reservation.js
  server/services/reservation/index.js
  server/services/reservation/model/reservations.js
  server/services/reservation/model/studygroup.js
  server/services/reservation/model/studyroom.js
  server/services/reservation/package.json
  server/services/reservation/query/queries.js
  server/services/reservation/test/reservation.test.js
  server/services/search/Search.js
  server/services/studygroup/StudyGroup.js
Labels: automerge

#302 Service/log -> develop/server
  .github/workflows/pr_to_service_test.yml
  server/lib/tcp/App.js
  server/services/search/index.js
  server/services/studygroup/index.js
  server/services/studyroom/index.js
Labels: MergeToDevelop

#315 Service/study group -> develop/server
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/api-gateway/routes/api/studyGroup/index.js
  server/services/studygroup/StudyGroup.js
  server/services/studygroup/__test__/groupCreateValidation.test.js
  server/services/studygroup/package.json
Labels: MergeToDevelop

#320 그룹 수정 페이지 완료, 그룹 카드 축소, 그룹 마감(모집) 상태 변경
  client/package.json
  client/public/image/new-logo-mini.png
  client/src/components/users/Header.jsx
  client/src/components/users/common/Location.jsx
  client/src/components/users/common/RangeSlider.jsx
  client/src/components/users/common/TagButtons.jsx
  client/src/components/users/groupCard/Body.jsx
  client/src/components/users/groupCard/Footer.jsx
  client/src/components/users/groupCard/Subtitle.jsx
  client/src/components/users/groupCard/Thumbnail.jsx
  client/src/components/users/groupCard/Time.jsx
  client/src/components/users/groupCard/Title.jsx
  client/src/components/users/groupCard/index.jsx
  client/src/components/users/groupCreate/ImageUploader.jsx
  client/src/components/users/groupCreate/ScheduleInput.jsx
  client/src/components/users/groupDetail/ApplyButtons.jsx
  client/src/components/users/groupDetail/Intro.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/lib/imageResize.jsx
  client/src/lib/utils.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/reducer/users/groupCreate.jsx
  client/src/reducer/users/groupDetail.jsx
  client/src/reducer/users/groupUpdate.jsx
Labels: FE, Group, automerge

#307 Develop/server
  .github/workflows/deploy.yml
  .github/workflows/dev_server_pr_test.yml
  .github/workflows/pr_test.yml
  server/.eslintrc.json
  server/api-gateway/README.md
  server/api-gateway/auth/passport.js
  server/api-gateway/index.js
  server/api-gateway/lib/avoidReservationCollision.js
  server/api-gateway/lib/getRoleFromToken.js
  server/api-gateway/middleware/auth/token-parser.js
  server/api-gateway/middleware/payment/inspectPayQueue.js
  server/api-gateway/middleware/payment/payQueueInspection.js
  server/api-gateway/middleware/payment/readyToPay.js
  server/api-gateway/package-lock.json
  server/api-gateway/package.json
  server/api-gateway/routes/api/payment/index.js
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/api-gateway/routes/api/studyGroup/index.js
  server/api-gateway/routes/api/studyroom/index.js
  server/api-gateway/routes/auth.partners.js
  server/api-gateway/routes/auth.users.js
  server/api-gateway/routes/auth/index.js
  server/api-gateway/routes/auth/partners.js
  server/api-gateway/routes/auth/users.js
  server/api-gateway/test/avoidReservationCollision.test.js
  server/api-gateway/test/getRoleFromToken.test.js
  server/lib/tcp/App.js
  server/package-lock.json
  server/package.json
  server/services/reservation/Reservation.js
  server/services/reservation/query/queries.js
  server/services/reservation/test/reservation.test.js
  server/services/search/Search.js
  server/services/search/elasticsearch.js
  server/services/search/index.js
  server/services/search/test/search.test.js
  server/services/studygroup/StudyGroup.js
  server/services/studygroup/__test__/groupCreateValidation.test.js
  server/services/studygroup/index.js
  server/services/studygroup/package.json
  server/services/studyroom/README.md
  server/services/studyroom/StudyRoom.js
  server/services/studyroom/index.js
  server/services/studyroom/jest-mongodb-config.js
  server/services/studyroom/jest.config.js
  server/services/studyroom/package-lock.json
  server/services/studyroom/package.json
  server/services/studyroom/queryResolver.js
  server/services/studyroom/test/studyroom.test.js
  server/startServices_deploy_ver.sh
Labels: 서비스업데이트

#330 https 서버 설정
  server/api-gateway/index.js
Labels: automerge

#318 사용자가 로그인 버튼을 눌렀을 때, 웹사이트에 접근 했을 때 요청하는 라우터 구현
  server/api-gateway/README.md
  server/api-gateway/middleware/auth/getUserByEmail.js
  server/api-gateway/middleware/auth/onlyUser.js
  server/api-gateway/middleware/auth/registerFirstTimeUser.js
  server/api-gateway/middleware/auth/token-parser.js
  server/api-gateway/middleware/auth/updateKakaoAccessToken.js
  server/api-gateway/routes/auth/users.js
Labels: BE, auth, automerge

#319 사용자의 로그인 로직 구현 및 안내 컴포넌트 구현
  client/src/components/users/Notice.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/LogoutButton.jsx
  client/src/pages/users/index.jsx
Labels: FE, auth

#321 그룹 수정 서비스 완료
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/api-gateway/routes/api/studyGroup/index.js
  server/lib/tcp/util.js
  server/services/search/Search.js
  server/services/studygroup/StudyGroup.js
Labels: BE, Group

#331 Page/main -> develop/client
  client/src/components/users/Notice.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/LogoutButton.jsx
  client/src/pages/users/index.jsx
Labels: MergeToDevelop

#332 Service/gateway -> develop/server
  server/api-gateway/README.md
  server/api-gateway/index.js
  server/api-gateway/middleware/auth/getUserByEmail.js
  server/api-gateway/middleware/auth/onlyUser.js
  server/api-gateway/middleware/auth/registerFirstTimeUser.js
  server/api-gateway/middleware/auth/token-parser.js
  server/api-gateway/middleware/auth/updateKakaoAccessToken.js
  server/api-gateway/routes/auth/users.js
Labels: MergeToDevelop

#334 Page/reservation -> develop/client
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/users/customOverlay/index.js
  client/src/components/users/customOverlay/overlay.scss
  client/src/lib/kakaoMapUtils.js
  client/src/lib/useWindowSize.js
  client/src/pages/users/reservation.jsx
Labels: MergeToDevelop

#335 Page/search
  client/package.json
  client/public/index.html
  client/src/components/users/Header.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/search.jsx
Labels: MergeToDevelop

#336 fix(location): 위치 정보 하드코딩한 것 픽스
  client/src/components/users/Header.jsx
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/lib/useAxios.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
Labels: bug

#339 Develop/client -> page/group_detail
  .github/workflows/deploy_dev_client.yml
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/users/Header.jsx
  client/src/components/users/Notice.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/LogoutButton.jsx
  client/src/components/users/customOverlay/index.js
  client/src/components/users/customOverlay/overlay.scss
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/lib/kakaoMapUtils.js
  client/src/lib/useAxios.jsx
  client/src/lib/useWindowSize.js
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/reservation.jsx
  client/src/pages/users/search.jsx
Labels: 서비스업데이트

#340 Develop/client -> page/main
  .github/workflows/deploy_dev_client.yml
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/users/Header.jsx
  client/src/components/users/customOverlay/index.js
  client/src/components/users/customOverlay/overlay.scss
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/lib/kakaoMapUtils.js
  client/src/lib/useAxios.jsx
  client/src/lib/useWindowSize.js
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/reservation.jsx
  client/src/pages/users/search.jsx
Labels: 서비스업데이트

#345 Develop/client -> page/main
  client/src/config.json
Labels: 서비스업데이트

#347 Hotfix -> server
  server/api-gateway/index.js
  server/api-gateway/lib/getRoleFromToken.js
  server/api-gateway/middleware/auth/token-parser.js
  server/api-gateway/models/user.js
  server/lib/redis/client.js
Labels: 서비스업데이트

#348 server -> apigateway
  .github/workflows/deploy.yml
  server/api-gateway/README.md
  server/api-gateway/index.js
  server/api-gateway/lib/getRoleFromToken.js
  server/api-gateway/middleware/auth/getUserByEmail.js
  server/api-gateway/middleware/auth/onlyUser.js
  server/api-gateway/middleware/auth/registerFirstTimeUser.js
  server/api-gateway/middleware/auth/token-parser.js
  server/api-gateway/middleware/auth/updateKakaoAccessToken.js
  server/api-gateway/models/user.js
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/api-gateway/routes/api/studyGroup/index.js
  server/api-gateway/routes/auth/users.js
  server/lib/redis/client.js
  server/services/studygroup/StudyGroup.js
Labels: 서비스업데이트

#351 develop-> search
  server/api-gateway/index.js
  server/api-gateway/lib/getRoleFromToken.js
  server/api-gateway/middleware/auth/token-parser.js
Labels: 서비스업데이트

#358 Feature/group refactor
  server/lib/redis/client.js
  server/lib/redis/index.js
  server/lib/redis/studygroup/index.js
  server/lib/redis/test/redis.test.js
  server/lib/tcp/App.js
  server/services/studygroup/StudyGroup.js
  server/services/studygroup/query.js
Labels: BE, Group

#363 Page/main -> develop/client
  client/src/components/users/UserInfo/index.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/index.jsx
Labels: FE, Group, MergeToDevelop

#344 그룹 입력(개설 및 수정) 카테고리 선택 시, css 적용
  client/src/components/users/groupCreate/Category.jsx
Labels: FE, Group

#364 Page/group edit -> develop/client
  client/src/components/users/groupCreate/Category.jsx
Labels: FE, Group, MergeToDevelop

#397 Page/main
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/pages/users/index.jsx
Labels: MergeToDevelop

#402 Page/main
  client/public/image/login-button.png
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/pages/users/index.jsx
Labels: MergeToDevelop

#383 그룹 서비스와 탐색 서비스의 CRUD 동기화 픽스
  server/lib/redis/studygroup/index.js
  server/services/studygroup/index.js
  server/services/studygroup/query.js
Labels: BE, Group, search

#384 클라이언트의 그룹 CRUD 픽스
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
Labels: FE, Group

#385 무한 스크롤을 위해 페이지 단위의 데이터 요청 url 적용
  client/src/pages/users/Main.jsx
Labels: FE

#403 Page/main
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
Labels: MergeToDevelop

#404 Develop/client -> page/group_detail
  .github/workflows/automerge.yml
  .github/workflows/deploy_dev_client.yml
  .gitignore
  client/public/image/login-button.png
  client/public/index.html
  client/src/App.js
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/index.jsx
  client/src/components/users/groupCreate/Category.jsx
  client/src/components/users/studyRoomList/ListCard.jsx
  client/src/components/users/studyRoomList/TextInfo.jsx
  client/src/components/users/studyRoomList/index.jsx
  client/src/config.json
  client/src/lib/kakaoMapUtils.js
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/reservation.jsx
Labels: 서비스업데이트

#405 Develop/client -> page/main
  .github/workflows/automerge.yml
  .github/workflows/deploy_dev_client.yml
  client/public/index.html
  client/src/App.js
  client/src/components/users/groupCreate/Category.jsx
  client/src/components/users/studyRoomList/ListCard.jsx
  client/src/components/users/studyRoomList/TextInfo.jsx
  client/src/components/users/studyRoomList/index.jsx
  client/src/lib/kakaoMapUtils.js
  client/src/pages/users/reservation.jsx
Labels: 서비스업데이트

#408 Page/main
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/LogoutButton.jsx
Labels: MergeToDevelop

#411 client -> search
  .github/workflows/automerge.yml
  .github/workflows/deploy_dev_client.yml
  .gitignore
  client/public/image/login-button.png
  client/public/index.html
  client/src/App.js
  client/src/components/users/Header.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/LogoutButton.jsx
  client/src/components/users/UserInfo/index.jsx
  client/src/components/users/groupCreate/Category.jsx
  client/src/components/users/studyRoomList/ListCard.jsx
  client/src/components/users/studyRoomList/TextInfo.jsx
  client/src/components/users/studyRoomList/index.jsx
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/config.json
  client/src/lib/kakaoMapUtils.js
  client/src/lib/useAxios.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/reservation.jsx
Labels: 서비스업데이트

#412 search -> search_suggest
  .github/workflows/automerge.yml
  .github/workflows/deploy_dev_client.yml
  .gitignore
  client/public/image/login-button.png
  client/public/index.html
  client/src/App.js
  client/src/components/users/Header.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/LogoutButton.jsx
  client/src/components/users/UserInfo/index.jsx
  client/src/components/users/groupCreate/Category.jsx
  client/src/components/users/studyRoomList/ListCard.jsx
  client/src/components/users/studyRoomList/TextInfo.jsx
  client/src/components/users/studyRoomList/index.jsx
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/config.json
  client/src/lib/kakaoMapUtils.js
  client/src/lib/useAxios.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/reservation.jsx
Labels: 서비스업데이트

#418 스터디 그룹 조작에 필요한 클라이언트 코드 작성
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/groupDetail/ApplyButtons.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/studySearchNavbar/StudyNavbarItem.jsx
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/reducer/users/groupDetail.jsx
Labels: FE, Group

#427 fix: 사용자 나이대가 없을 때 발생하는 오류 수정
  client/src/components/users/UserInfo/LoginButton.jsx
Labels: bug

#417 Feature/group detail router
  server/api-gateway/routes/api/studyGroup/ctrl.js
  server/api-gateway/routes/api/studyGroup/index.js
Labels: BE, Group

#416 스터디 조작 기능에 대한 서비스 작성
  server/services/studygroup/StudyGroup.js
  server/services/studygroup/models/Users.js
  server/services/studygroup/query.js
Labels: BE, Group

#429 결제 서비스의 쿼리 기능 작성 (1. inspectQueue, 2. approvePayment, 3. removeInQueue)
  server/services/payment/Payment.js
  server/services/payment/README.md
  server/services/payment/model/payment.js
  server/services/payment/query/queries.js
  server/services/payment/query/util.js
  server/services/payment/test/avoidReservationCollision.test.js
  server/services/payment/test/getQueueByUserId.test.js
Labels: automerge, payment

#430 Feature/be payment routes
  server/api-gateway/README.md
  server/api-gateway/lib/avoidReservationCollision.js
  server/api-gateway/lib/getRoleFromToken.js
  server/api-gateway/middleware/auth/token-parser.js
  server/api-gateway/middleware/payment/inspectPayQueue.js
  server/api-gateway/middleware/payment/readyToPay.js
  server/api-gateway/routes/api/payment/index.js
  server/api-gateway/test/avoidReservationCollision.test.js
  server/api-gateway/test/getRoleFromToken.test.js
  server/api-gateway/test/jwt-generator.test.js
  server/api-gateway/test/response-token.test.js
Labels: BE, payment

#434 Develop/client -> page/main
  client/src/components/users/Header.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/common/Location.jsx
  client/src/components/users/groupDetail/ApplyButtons.jsx
  client/src/components/users/groupDetail/Intro.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/studySearchNavbar/StudyNavbarItem.jsx
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/components/users/suggestDropDown/index.jsx
  client/src/lib/coord2string.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/search.jsx
  client/src/reducer/users/groupDetail.jsx
Labels: 서비스업데이트

#445 page/main -> develop/client
  client/package-lock.json
  client/package.json
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/customOverlay/index.jsx
  client/src/components/users/groupCreate/TagInput.jsx
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/components/users/studySearchNavbar/StudyNavbarItem.jsx
  client/src/lib/coord2string.jsx
  client/src/lib/infiniteScrollEventHandler.js
  client/src/pages/users/Main.jsx
  client/src/pages/users/reservation.jsx
  client/src/reducer/users/index.jsx
Labels: MergeToDevelop

#447 client -> search
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/image/github-logo.png
  client/public/image/notion-gray.png
  client/public/index.html
  client/src/App.js
  client/src/components/Footer.jsx
  client/src/components/users/Header.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/common/Location.jsx
  client/src/components/users/customOverlay/index.jsx
  client/src/components/users/groupCreate/TagInput.jsx
  client/src/components/users/groupDetail/ApplyButtons.jsx
  client/src/components/users/groupDetail/Intro.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/components/users/studySearchNavbar/StudyNavbarItem.jsx
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/lib/coord2string.jsx
  client/src/lib/useInfiniteScroll.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/reservation.jsx
  client/src/pages/users/search.jsx
  client/src/reducer/users/groupCreate.jsx
  client/src/reducer/users/groupDetail.jsx
  client/src/reducer/users/groupUpdate.jsx
  client/src/reducer/users/index.jsx
Labels: 서비스업데이트

#448 Page/main
  client/src/pages/users/Main.jsx
  client/src/reducer/users/groupCreate.jsx
  client/src/reducer/users/index.jsx
Labels: MergeToDevelop

#456 Page/payment
  client/package-lock.json
  client/package.json
  client/src/components/users/Receipt/ReservationInfo.jsx
  client/src/components/users/Receipt/StudyroomInfo.jsx
  client/src/components/users/Receipt/index.jsx
  client/src/components/users/Receipt/util.js
  client/src/pages/users/index.jsx
  client/src/pages/users/payment.jsx
Labels: MergeToDevelop

#459 예약 페이지 개발을 위한 업데이트 PR
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/image/github-logo.png
  client/public/image/login-button.png
  client/public/image/notion-gray.png
  client/public/index.html
  client/src/App.js
  client/src/components/Footer.jsx
  client/src/components/users/Header.jsx
  client/src/components/users/Receipt/ReservationInfo.jsx
  client/src/components/users/Receipt/StudyroomInfo.jsx
  client/src/components/users/Receipt/index.jsx
  client/src/components/users/Receipt/util.js
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/UserInfo/LogoutButton.jsx
  client/src/components/users/UserInfo/index.jsx
  client/src/components/users/common/Location.jsx
  client/src/components/users/customOverlay/index.jsx
  client/src/components/users/groupCreate/Category.jsx
  client/src/components/users/groupCreate/TagInput.jsx
  client/src/components/users/groupDetail/ApplyButtons.jsx
  client/src/components/users/groupDetail/Intro.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/components/users/studySearchNavbar/StudyNavbarItem.jsx
  client/src/components/users/studySearchNavbar/index.jsx
  client/src/components/users/suggestDropDown/index.jsx
  client/src/config.json
  client/src/lib/coord2string.jsx
  client/src/lib/kakaoMapUtils.js
  client/src/lib/useInfiniteScroll.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/payment.jsx
  client/src/pages/users/reservation.jsx
  client/src/pages/users/search.jsx
  client/src/reducer/users/groupCreate.jsx
  client/src/reducer/users/groupDetail.jsx
  client/src/reducer/users/groupUpdate.jsx
  client/src/reducer/users/index.jsx
Labels: 서비스업데이트

#463 fix(main_carousel): 새로고침시, 사용자가 소속된 그룹 캐로셀이 안 나타나는 점 수정
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/pages/users/Main.jsx
  client/src/reducer/users/index.jsx
Labels: FE, Group, MergeToDevelop, carousel

#466 캐로셀 버그 픽스 및 스타일 수정
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/pages/users/Main.jsx
Labels: FE, Group, carousel

#467 Page/reservation
  client/public/index.html
  client/src/components/users/customOverlay/index.jsx
  client/src/lib/kakaoMapUtils.js
  client/src/pages/users/reservation.jsx
Labels: MergeToDevelop

#468 캐로셀 버그 수정, 인피니티 스크롤 높이 재설정
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/lib/useInfiniteScroll.jsx
  client/src/pages/users/Main.jsx
Labels: FE

#470 Develop/client -> search page
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/users/Receipt/ReservationInfo.jsx
  client/src/components/users/Receipt/StudyroomInfo.jsx
  client/src/components/users/Receipt/index.jsx
  client/src/components/users/Receipt/util.js
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/customOverlay/index.jsx
  client/src/components/users/groupDetail/ApplyButtons.jsx
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/lib/kakaoMapUtils.js
  client/src/lib/useInfiniteScroll.jsx
  client/src/lib/utils.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/index.jsx
  client/src/pages/users/payment.jsx
  client/src/pages/users/reservation.jsx
  client/src/reducer/users/groupCreate.jsx
  client/src/reducer/users/groupUpdate.jsx
  client/src/reducer/users/index.jsx
Labels: 서비스업데이트

#471 클라이언트 코드 확인 후 예약 페이지 브랜치 동기화
  client/src/components/users/Header.jsx
  client/src/components/users/UserInfo/LoginButton.jsx
  client/src/components/users/common/TagButtons.jsx
  client/src/components/users/groupCard/Body.jsx
  client/src/components/users/groupCard/index.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/components/users/myStudyCardCarousel/Card.jsx
  client/src/components/users/myStudyCardCarousel/index.jsx
  client/src/lib/useInfiniteScroll.jsx
  client/src/lib/utils.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupCreate.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/groupUpdate.jsx
  client/src/pages/users/reservation.jsx
  client/src/pages/users/search.jsx
  client/src/reducer/users/groupUpdate.jsx
  client/src/reducer/users/index.jsx
Labels: 서비스업데이트

#475 page/reservation 브랜치 최신화
  client/src/pages/users/search.jsx
Labels: 서비스업데이트

#476 잔버그 수정 및 그룹 검색 시, 위치 정보 표시
  client/src/lib/coord2string.jsx
  client/src/lib/useInfiniteScroll.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/search.jsx
Labels: FE, Group, search

#478 카테고리 검색 결과 라우팅 추가
  client/src/components/users/groupDetail/Header.jsx
  client/src/components/users/groupDetail/Main.jsx
  client/src/components/users/studySearchNavbar/StudyNavbarItem.jsx
  client/src/pages/users/Main.jsx
  client/src/pages/users/groupDetail.jsx
  client/src/pages/users/index.jsx
  client/src/reducer/users/groupCreate.jsx
Labels: FE, Group, search

#479 카테고리 버튼 수정
  client/src/components/users/studySearchNavbar/StudyNavbarItem.jsx
Labels: FE
